Sales & Stocks Management System [SSMS]/PL/Controllers/CustomerController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.Repositories;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PL.Models;
using System.Linq;

namespace PL.Controllers
{
    public class CustomerController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CustomerController(UnitOfWork unitOfWork , IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<Customer> customers = _unitOfWork.CustomerRepository.GetAll();
            IEnumerable<CustomerViewModel> MappedCustomers = _mapper.Map<IEnumerable<CustomerViewModel>>(customers);
            return View(MappedCustomers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var customer = _mapper.Map<Customer>(model);

                _unitOfWork.CustomerRepository.Add(customer);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            return Details(id , "Edit");
        }

        [HttpPost]
        public IActionResult Edit(CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                var mappedCustomer = _mapper.Map<Customer>(model);

                _unitOfWork.CustomerRepository.Update(mappedCustomer);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Details(int id , string ViewName = "Details")
        {
            var customer = _unitOfWork.CustomerRepository.Entities.Include(C => C.Invoices).ThenInclude(inv => inv.InvoiceItems).Where(C => C.Id == id).FirstOrDefault();
            if(customer == null)
                   return NotFound();
            var mappedCustomer = _mapper.Map<CustomerViewModel>(customer);
            return View(ViewName , mappedCustomer);
        }

        public IActionResult Delete(int id)
        {
            return Details(id,"Delete");
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirme([FromRoute]int id , CustomerViewModel model)
        {
            if (model.Id != id) return BadRequest();
            var customer = _unitOfWork.CustomerRepository.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }

            _unitOfWork.CustomerRepository.Delete(customer);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Sales & Stocks Management System [SSMS]/PL/Controllers/ProductController.cs
using AutoMapper;
using BLL.Repositories;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PL.Models;

namespace PL.Controllers
{
    public class ProductController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public ProductController(UnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        // GET: ProductController
        public ActionResult Index(string name, string category, int? minStock, int? maxStock)
        {
            IEnumerable<Product> products = _unitOfWork.ProductRepository.GetAll();

            // Apply filters
            if (!string.IsNullOrEmpty(name))
            {
                products = products.Where(p => p.Name.Contains(name));
            }

            if (!string.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Contains(category));
            }

            if (minStock.HasValue)
            {
                products = products.Where(p => p.StockQuantity >= minStock.Value);
            }

            if (maxStock.HasValue)
            {
                products = products.Where(p => p.StockQuantity <= maxStock.Value);
            }

            // Map products to ProductViewModel
            IEnumerable<ProductViewModel> MappedProducts = _mapper.Map<IEnumerable<ProductViewModel>>(products);

            return View(MappedProducts);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            var product = _unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            var productViewModel = _mapper.Map<ProductViewModel>(product);
            return View(productViewModel);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel productViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var product = _mapper.Map<Product>(productViewModel);
                    _unitOfWork.ProductRepository.Add(product);
                    _unitOfWork.Save();
                    return RedirectToAction(nameof(Index));
                }
                return View(productViewModel);
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            var productViewModel = _mapper.Map<ProductViewModel>(product);
            productViewModel.LastPrice = product.ProductPrices.LastOrDefault()?.Price??0;
            return View(productViewModel);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([FromRoute] int id, ProductViewModel productViewModel)
        {
            try
            {
                if(id != productViewModel.Id)
                    return BadRequest();

                if (ModelState.IsValid)
                {
                    Product ?product = _unitOfWork.ProductRepository.GetById(id);
                    if (product == null) return NotFound();
                    product.Name = productViewModel.Name;
                    product.Description = productViewModel.Description;
                    product.Category = productViewModel.Category;
                    product.StockQuantity = productViewModel.StockQuantity;

                    if (product.ProductPrices.Any())
                    {
                        var lastPrice = product.ProductPrices.Last();
                        lastPrice.Price = productViewModel.LastPrice;
                    }
                    else
                    {
                        // Optionally handle cases where there are no price entries
                        product.ProductPrices.Add(new ProductPrice { Price = productViewModel.LastPrice, DateTime = DateTime.Now });
                    }

                    _unitOfWork.ProductRepository.Update(product);
                    _unitOfWork.Save();
                    return RedirectToAction(nameof(Index));
                }
                return View(productViewModel);
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete([FromRoute]int id)
        {
            var product = _unitOfWork.ProductRepository.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            
            var productViewModel = _mapper.Map<ProductViewModel>(product);
            return View(productViewModel);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([FromRoute]int id, ProductViewModel collection)
        {
            try
            {
                if(collection.Id != id) return BadRequest();

                var product = _unitOfWork.ProductRepository.GetById(id);
                if (product == null)
                {
                    return NotFound();
                }

                _unitOfWork.ProductRepository.Delete(product);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Sales & Stocks Management System [SSMS]/PL/Controllers/SalesController.cs
using AutoMapper;
using BLL.Repositories;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PL.Models;
using System.Linq.Expressions;
using System.Transactions;

namespace PL.Controllers
{
    public class SalesController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SalesController(UnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<SaleInvoice> SalesInvoices = _unitOfWork.SalesInvoiceRepository.GetAll();
            var MappedSalesInoices = _mapper.Map<IEnumerable<InvoiceViewModel>>(SalesInvoices);
            return View(MappedSalesInoices);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new InvoiceViewModel()
            {
                Date = DateTime.Now,
                InvoiceItems = new List<InvoiceItem> { new InvoiceItem() }
            };

            PopulateProducts(); // Populate ViewBag with products

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(InvoiceViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.CalcTotal();
                    SaleInvoice saleInvoice = _mapper.Map<SaleInvoice>(model);

                    using (TransactionScope SaleTran = new TransactionScope())
                    {
                        foreach (var item in saleInvoice.InvoiceItems)
                        {
                            var product = _unitOfWork.ProductRepository.GetById(item.ProductId);
                            if (item.Quantity > product.StockQuantity)
                            {
                                ModelState.AddModelError("", $"Available from {product.Name}: {product.StockQuantity}");
                                PopulateProducts(); // Ensure products are available in the ViewBag
                                return View(model);
                            }
                            product.StockQuantity -= item.Quantity;
                        }
                        _unitOfWork.SalesInvoiceRepository.Add(saleInvoice);
                        _unitOfWork.Save();
                        SaleTran.Complete();
                    }
                    return RedirectToAction(nameof(Index));
                }

                PopulateProducts(); // Ensure products are available in the ViewBag
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.InnerException.Message);
                PopulateProducts(); // Ensure products are available in the ViewBag
                return View(model);
            }
        }

        private void PopulateProducts()
        {
            var products = _unitOfWork.ProductRepository.GetAll()
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                }).ToList();
            ViewBag.Products = products;
        }
    }
}

Sales & Stocks Management System [SSMS]/PL/Controllers/SupplierController.cs
using AutoMapper;
using BLL.Repositories;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PL.Models;

namespace PL.Controllers
{
    public class SupplierController : Controller
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SupplierController(UnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<Supplier> Suppliers = _unitOfWork.SupplierRepository.GetAll();
            IEnumerable<SupplierViewModel> MappedSuppliers = _mapper.Map<IEnumerable<SupplierViewModel>>(Suppliers);
            return View(MappedSuppliers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(SupplierViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Supplier = _mapper.Map<Supplier>(model);

                _unitOfWork.SupplierRepository.Add(Supplier);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            return Details(id, "Edit");
        }

        [HttpPost]
        public IActionResult Edit(SupplierViewModel model)
        {
            if (ModelState.IsValid)
            {

                var mappedSupplier = _mapper.Map<Supplier>(model);

                _unitOfWork.SupplierRepository.Update(mappedSupplier);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Details(int id, string ViewName = "Details")
        {
            var Supplier = _unitOfWork.SupplierRepository.Entities.Include(C => C.Invoices).Where(C => C.Id == id).FirstOrDefault();
            if (Supplier == null)
                return NotFound();
            var mappedSupplier = _mapper.Map<SupplierViewModel>(Supplier);
            return View(ViewName, mappedSupplier);
        }

        public IActionResult Delete(int id)
        {
            return Details(id, "Delete");
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirme([FromRoute] int id, SupplierViewModel model)
        {
            if (model.Id != id) return BadRequest();
            var Supplier = _unitOfWork.SupplierRepository.GetById(id);
            if (Supplier == null)
            {
                return NotFound();
            }

            _unitOfWork.SupplierRepository.Delete(Supplier);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Sales & Stocks Management System [SSMS]/PL/Views/Shared/ButtonsPartial.cshtml
@Model int 

Sales & Stocks Management System [SSMS]/PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/css/sideparstylesheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="~/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-2">
                <div class="sidebar shadow">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center active" asp-action="index" asp-controller="Home">
                                <i class="fa-solid fa-house me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                DashBoard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" asp-controller="Sales" asp-action="Index">
                                <i class="fa-solid fa-minus me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Sales
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="#">
                                <i class="fa-solid fa-plus me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Purchases
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" asp-action="index" asp-controller="Product">
                                <i class="fa-solid fa-warehouse me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Inventory
                            </a>
                           
                        </li>
                        <li class="nav-item ">

                            <a class="nav-link d-flex align-items-center" asp-controller="Customer" asp-action="Index">
                                <i class="fa-solid fa-users me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Customers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" asp-controller="Supplier" asp-action="Index">
                                <i class="fa-solid fa-users-gear me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Suppliers
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" href="#">
                                <i class="fa-solid fa-chart-simple me-2"></i> <!-- "me-2" adds some margin on the right side of the icon -->
                                Reports
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Main Content -->
           
                <div class="col-md-9">
                    <Center>
                      @RenderBody()
                    </Center>
                </div>
           
        </div>
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>